*** Settings ***
####################################################################################################################################################################
# PLEASE DO NOT EDIT THIS FILE. THIS IS A TEMPLATE ROBOT FILE.    #
Documentation       This is a sample robot file to show how the test cases will look like after creation.
...                 - ``Date Of Implementation : <DD-MMM-YYYY> / Author : <Tester Name>``\n
...                 - ``Last Updated : <DD-MMM-YYYY> / Updated By : <Tester Name>``\n
...                 - ``User Story ID : [https://crdn.codebeamer.com/item/<USID> | <USID>]``\n
...                 - ``Pre-Requisites : <Call out any dependencies>``
####################################################################################################################################################################
Metadata            Version    1.0
Metadata            Type    <Normal/DataDriven/Keyword/Hybrid>
Metadata            Steps    <Number of Steps>

####################################################################################################################################################################
Library             RequestsLibrary

Name                Template Test Suite
